<?php
/***************************************************************************
	@extension	: Dealer Inquiry Extension.
	@copyright	: Copyright (c) 2015 Capacity Web Solutions.
	( http://www.capacitywebsolutions.com )
	@author		: Capacity Web Solutions Pvt. Ltd.
	@support	: magento@capacitywebsolutions.com	
***************************************************************************/

 $code =  trim($this->getRandomCode()); 
 $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat'); 

 ?>
 <script>
function clearFileInputField(tagId) {
    document.getElementById(tagId).innerHTML = 
                    document.getElementById(tagId).innerHTML;
}
</script>
<?php if($this->getCaptchaHide()): ?>
<script>
jQuery(document).ready(function(){
jQuery("#img_refresh").click(function(){
   jQuery("#captcha").load(location.href + " #captcha");
	});

});
</script>
<script language="JavaScript" type="text/JavaScript">
    function captchacode()
    {
		var captcha = document.getElementById('capt').value;
		var captcha_code = document.getElementById('captcha_code').value;
		if (captcha == "")
		{
			return true;
		}
		if (captcha==captcha_code)
		{
			return true;
		}
		else
		{
			alert ("Captcha code does not match!");
			return false;
		}
	}
</script>
<?php endif; ?>

<div id="about-copy" class="inquiryForm">
	<h1><img src="<?php echo $this->getSkinUrl('images/inquiry-icon.png') ?>" alt="" /><?php if($this->getHeading()): ?><?php echo $this->__($this->getHeading()); ?><?php endif; ?></h1>
	<p><?php if($this->getDesc()): ?><?php echo $this->getDesc(); ?><?php endif; ?></p>
    <?php if($this->getIndicates()) { ?>
		<div class="indicates"><span class="required"><em>*</em></span><?php echo $this->__($this->getIndicates()); ?></div>
	<?php } ?>
	
	<form name="dealerInquiry" id="dealerInquiry" action="<?php echo $this->getUrl("inquiry/index/thanks"); ?>" method="post" enctype="multipart/form-data">
    	<div class="fieldset">
        	<ul class="form-list">
            	<li class="fields">
                	<div class="field">
						<label><?php if($this->getFirstName()): ?><?php echo $this->getFirstName(); ?><?php else: ?><?php echo "First Name:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="firstname" id="firstname" size="45" class="input-text required-entry input-box" />
                        </div>
                    </div>
                    <?php if($this->getLastNameHide()): ?> 
                    <div class="field">
                    	<label><?php if($this->getLastName()): ?><?php echo $this->getLastName(); ?><?php else: ?><?php echo "Last Name:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="lastname" size="45" class="input-text required-entry" />
                        </div>
                    </div>
                    <?php endif;  ?>
                </li>
                <li class="fields">
                	<div class="field">
                    	<label><?php if($this->getCompanyName()): ?><?php echo $this->getCompanyName(); ?><?php else: ?><?php echo "Company Name:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="company" size="45" class="input-text required-entry" />
                        </div>
                    </div>
				
					<?php if($this->getVatNumberHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getVatNumber()): ?><?php echo $this->getVatNumber(); ?><?php else: ?><?php echo "Tax/VAT Number:"; ?><?php endif;  ?></label>
                        <div class="input-box">
                        	<input type="text" name="taxvat" size="45" class="input-text" /> 
                        </div>
                    </div>
                    <?php endif; ?>
					
					<?php if($this->getAddressHide()): ?>  
                	<div class="field">
                    	<label><?php if($this->getAddress()): ?><?php echo $this->getAddress(); ?> <?php else: ?><?php echo "Address:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
	                        <textarea name="address" cols="42" rows="1" class="input-text required-entry"></textarea>
                        </div>
                    </div>
                    <?php endif; ?>
                </li>
                <li class="fields">
                    <?php if($this->getCityHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getCity()): ?><?php echo $this->getCity(); ?><?php else: ?><?php echo "City:"; ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="city" size="45" class="input-text required-entry" /> 
                        </div>
                    </div>
                    <?php endif; ?>
                    <?php if($this->getStateHide()): ?>
                	 <div class="field">
                     	<label><?php if($this->getState()): ?><?php echo $this->getState(); ?><?php else: ?><?php echo "State / Province:"; ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
	                        <input type="text" name="state" size="45" class="input-text required-entry" />
                        </div>
                     </div>
                     <?php endif; ?>
                </li>
                <li class="fields">
                     <?php if($this->getCountryHide()): ?>
                     <div class="field">
                     	<label><?php if($this->getCountry()): ?><?php echo $this->getCountry(); ?><?php else: ?><?php echo "Country:"; ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                            <select name="country" id="country" class="drop" class="input-text required-entry">
                                <?php
                                    $countryCode = Mage::getStoreConfig('general/country/default');
                                    $country_name=Mage::app()->getLocale()->getCountryTranslation($countryCode);
                                    $collection = Mage::getModel('directory/country')->getCollection();
                                    foreach ($collection as $country)
                                    {
										$cid = $country->getId();
										$cname = $country->getName(); 
									?>
										<option value="<?php echo $cid.'$$$'.$cname; ?>"<?php if($cid == $countryCode) echo "SELECTED" ?> ><?php echo $cname; ?></option>
									<?php 
									} 
                                ?>
                            </select>
                        </div>
                     </div>
                     <?php endif; ?>
                     <?php if($this->getPostalCodeHide()): ?>
                  	 <div class="field">
                    	<label><?php if($this->getPostalCode()): ?><?php echo $this->getPostalCode(); ?><?php else: ?><?php echo "ZIP / Postal Code:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                 			<input type="text" name="zip" id="zip" size="45" maxlength="10" class="required-entry input-text required-entry input-text required-entry validation-passed" />
                        </div>
                     </div>
                    <?php endif; ?>
                </li>
                <li class="fields">
                    <div class="field">
                    	<label><?php if($this->getContactNumber()): ?><?php echo $this->getContactNumber(); ?><?php else: ?><?php echo "Contact Number:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="phone" size="45" onKeyPress="return isNumberKey(event)" maxlength="15" class="input-text validate input-text required-entry"/>
                        </div>
                    </div>
				</li>
				 <li class="fields">
                    <div class="field">
	                	<label><?php if($this->getEmail()): ?><?php echo $this->getEmail(); ?><?php else: ?><?php echo "Email:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
    	            	<div class="input-box">
                        	<input type="text" name="email" size="45" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <?php if($this->getWebsiteHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getWebsite()): ?><?php echo $this->getWebsite(); ?><?php else: ?><?php echo "Website:"; ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="website" size="45" class="input-text" /> 
                        </div>
                    </div>
                    <?php endif; ?>
                    <div class="field">
                        <label><?php if($this->getDescription()): ?><?php echo $this->getDescription(); ?><?php else: ?><?php echo "Business Description:"; ?><?php endif; ?></label>
                        <div class="input-box">
                            <textarea name="desc" cols="75" rows="2" class="input-text"></textarea>
                        </div>
                    </div>
                </li>
				<li class="fields">
					<?php if($this->getDateTimeHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getDateTime()): ?><?php echo $this->getDateTime(); ?><?php else: ?><?php echo "Date Time:"; ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="date_time" id="date_time" size="45" class="input-text validate-date" placeholder="dd/mm/yyyy HH:MM:SS"/>  <img title="Select date" id="date-picker-cal" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>">
                        </div>
                    </div>
					<script type="text/javascript">// <![CDATA[
					Calendar.setup({
						inputField : 'date_time',
						ifFormat : '%d/%m/%Y %H:%M:%S',
						button : 'date-picker-cal',
						align : 'Br',
						singleClick : true ,
						showsTime : true
					});
					
					// ]]></script>
					<?php endif; ?>
					<?php if($this->getUploadFileHide()): ?>
					<div class="field">
                    	<label><?php if($this->getUploadFile()): ?><?php echo $this->getUploadFile(); ?><?php else: ?><?php echo "Upload File:"; ?><?php endif; ?></label>
                        <div class="input-box"  id="uploadFile_div">
                        	<input type="file" id="file" name="file[]" size="45" class="input-text" multiple="multiple"/>&nbsp;&nbsp;&nbsp;
							<a id="clearfile" onclick="clearFileInputField('uploadFile_div')" 
                         href="javascript:void(0);">Clear Uploaded File</a>
						 </div>
                    </div>
					<?php endif; ?>
				</li>
				<li class="fields">
                    <?php if($this->getFieldOneHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getExtraFieldOne()): ?><?php echo $this->getExtraFieldOne(); ?><?php else: ?><?php echo "Extra Field 1:"; ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="extra_field_one" size="45" class="input-text" /> 
                        </div>
                    </div>
                    <?php endif; ?>
					<?php if($this->getFieldTwoHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getExtraFieldTwo()): ?><?php echo $this->getExtraFieldTwo(); ?><?php else: ?><?php echo "Extra Field 2:"; ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="extra_field_two" size="45" class="input-text" /> 
                        </div>
                    </div>
                    <?php endif; ?>
					<?php if($this->getFieldThreeHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getExtraFieldThree()): ?><?php echo $this->getExtraFieldThree(); ?><?php else: ?><?php echo "Extra Field 3:"; ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="extra_field_three" size="45" class="input-text" /> 
                        </div>
                    </div>
                    <?php endif; ?>
				</li>
                <li class="fields last">
				<?php if($this->getCaptchaHide()): ?>  
                	<label>Capctha<span class="required"><em>*</em></span></label>
                    <div class="captcha-main">
                        <div id="captcha" class="captcha-left">
                            <b><?php echo $code; ?></b>&nbsp; 
                            <input type="hidden" value="<?php echo $code; ?>" id="captcha_code" size="45" name="captcha_code">
                        </div> 
                    </div> 
                    <div id="img_refresh"><img src="<?php echo $this->getSkinUrl('images/refresh.png') ?>"></div>
                    <div class="clear"></div>
                    <input type="text" name="captcha" id="capt" size="24" value="" class="input-text required-entry" />
                <?php endif; ?>
                </li>
        	</ul>
            <div class="clear"></div>
            <div class="button-set">
					<button type="submit" name="SUBMIT"  class="button" value="SUBMIT" onclick="return captchacode() ;"><span><span><?php if($this->getBtnText()): ?><?php echo $this->getBtnText(); ?><?php else: ?><?php echo "Submit"; ?><?php endif;  ?></span></span></button>
            </div>
        </div>
    </form>
    <div class="clear"></div>
</div>
<script type="text/javascript">
//< ![CDATA[
var customForm = new VarienForm('dealerInquiry');
//]]>
	function isNumberKey(evt)
	{
		 var charCode = (evt.which) ? evt.which : evt.keyCode
		 if (charCode > 31 && (charCode < 48 || charCode > 57))
		 {
		 	return false;
		}		
		 return true;
	} 

</script>
