<?php
/***************************************************************************
	@extension	: Dealer Inquiry Extension.
	@copyright	: Copyright (c) 2015 Capacity Web Solutions.
	( http://www.capacitywebsolutions.com )
	@author		: Capacity Web Solutions Pvt. Ltd.
	@support	: magento@capacitywebsolutions.com	
***************************************************************************/
?>

<?php $code =  trim($this->getRandomCode()); 
$_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat'); ?>
<script>
function clearFileInputField(tagId) {
    document.getElementById(tagId).innerHTML = 
                    document.getElementById(tagId).innerHTML;
}
</script>
<?php if($this->getCaptchaHide()): ?>
<script>
	function refresh(){
		var image = document.getElementById("captcha_image");
		<?php 
		$url = Mage::helper('adminhtml')->getUrl('inquiry/index/refresh');
		?>
		var urlpage = '<?php echo $url;?>';
		new Ajax.Request(urlpage, {
			method:'get',
			onSuccess: function(transport) {
			var image_name = transport.responseText.evalJSON(true);
			image.src = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."inquiry/captcha/";?>'+image_name;
			},
			onFailure: function() { alert('Something went wrong...'); }
	
		});
	}
</script>
<?php endif; ?>
<div id="about-copy" class="inquiryForm">
	<h1><img src="<?php echo $this->getSkinUrl('images/inquiry/inquiry-icon.png') ?>" alt="" /><?php if($this->getHeading()): ?><?php echo $this->__($this->getHeading()); ?><?php endif; ?></h1>
	<p><?php if($this->getDesc()): ?><?php echo $this->getDesc(); ?><?php endif; ?></p>
    <?php if($this->getIndicates()) { ?>
		<div class="indicates"><span class="required"><em>*</em></span><?php echo $this->__($this->getIndicates()); ?></div>
	<?php } ?>
	
	<form name="dealerInquiry" id="dealerInquiry" action="<?php echo $this->getUrl("inquiry/index/save"); ?>" method="post" enctype="multipart/form-data">
    	<div class="fieldset">
        	<ul class="form-list">
            	<li class="fields">
                	<div class="field">
						<label><?php if($this->getFirstName()): ?><?php echo $this->__($this->getFirstName()); ?><?php else: ?><?php echo $this->__("First Name:"); ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="firstname" id="firstname" size="45" class="input-text required-entry input-box" value="<?php echo $this->escapeHtml($this->getFormData()->getFirstname()) ?>"/>
                        </div>
                    </div>
                    <?php if($this->getLastNameHide()): ?> 
                    <div class="field">
                    	<label><?php if($this->getLastName()): ?><?php echo $this->__($this->getLastName()); ?><?php else: ?><?php echo $this->__("Last Name:"); ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="lastname" size="45" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getLastname()) ?>"/>
                        </div>
                    </div>
                    <?php endif;  ?>
                </li>
                <li class="fields">
                	<div class="field">
                    	<label><?php if($this->getCompanyName()): ?><?php echo $this->__($this->getCompanyName()); ?><?php else: ?><?php echo $this->__("Company Name:"); ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="company" size="45" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>"/>
                        </div>
                    </div>
				
					<?php if($this->getVatNumberHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getVatNumber()): ?><?php echo $this->__($this->getVatNumber()); ?><?php else: ?><?php echo $this->__("Tax/VAT Number:"); ?><?php endif;  ?></label>
                        <div class="input-box">
                        	<input type="text" name="taxvat" size="45" class="input-text" value="<?php echo $this->escapeHtml($this->getFormData()->getTaxvat()) ?>"/> 
                        </div>
                    </div>
                    <?php endif; ?>
                </li>
                
                <li class="fields">
					<?php if($this->getAddressHide()): ?>  
                        <div class="field">
                            <label><?php if($this->getAddress()): ?><?php echo $this->__($this->getAddress()); ?> <?php else: ?><?php echo $this->__("Address:"); ?><?php endif; ?><span class="required"><em>*</em></span></label>
                            <div class="input-box">
                                <textarea name="address" cols="42" rows="1" class="input-text required-entry"><?php echo $this->escapeHtml($this->getFormData()->getAddress()) ?></textarea>
                            </div>
                        </div>
                    <?php endif; ?>
                    
                    <?php if($this->getCityHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getCity()): ?><?php echo $this->__($this->getCity()); ?><?php else: ?><?php echo $this->__("City:"); ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="city" size="45" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>"/> 
                        </div>
                    </div>
                    <?php endif; ?>
                </li>
                <li class="fields">
                    <?php if($this->getStateHide()): ?>
                	 <div class="field">
                     	<label><?php if($this->getState()): ?><?php echo $this->__($this->getState()); ?><?php else: ?><?php echo $this->__("State / Province:"); ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
	                        <input type="text" name="state" size="45" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getState()) ?>"/>
                        </div>
                     </div>
                     <?php endif; ?>
                     
					<?php if($this->getCountryHide()): ?>
                     <div class="field">
                     	<label><?php if($this->getCountry()): ?><?php echo $this->__($this->getCountry()); ?><?php else: ?><?php echo $this->__("Country:"); ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
						<?php $country_sess = $this->escapeHtml($this->getFormData()->getCountry()) ?>
                            <select name="country" id="country" class="drop" class="input-text required-entry">
                                <?php
                                    $countryCode = Mage::getStoreConfig('general/country/default');
                                    $country_name=Mage::app()->getLocale()->getCountryTranslation($countryCode);
                                    $collection = Mage::getModel('directory/country')->getCollection();
                                    foreach ($collection as $country)
                                    {
										$cid = $country->getId();
										$cname = $country->getName(); 
										$country = $cid.'$$$'.$cname;
										
									?>
										<option value="<?php echo $cid.'$$$'.$cname; ?>"<?php 
										if($country==$country_sess || (empty($country_sess) && $cid == $countryCode)){ 
										echo "SELECTED";
										} ?> ><?php echo $cname; ?></option>
									<?php 
									} 
                                ?>
                            </select>
                        </div>
                     </div>
                     <?php endif; ?> 
                </li>
                <li class="fields">
                     <?php if($this->getPostalCodeHide()): ?>
                  	 <div class="field">
                    	<label><?php if($this->getPostalCode()): ?><?php echo $this->__($this->getPostalCode()); ?><?php else: ?><?php echo $this->__("ZIP / Postal Code:"); ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                 			<input type="text" name="zip" id="zip" size="45" maxlength="10" class="required-entry input-text validation-passed" value="<?php echo $this->escapeHtml($this->getFormData()->getZip()) ?>"/>
                        </div>
                     </div>
                    <?php endif; ?>
                    
                    <div class="field">
                    	<label><?php if($this->getContactNumber()): ?><?php echo $this->__($this->getContactNumber()); ?><?php else: ?><?php echo $this->__("Contact Number:"); ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="phone" size="45" onKeyPress="return isNumberKey(event)" maxlength="15" class="input-text validate required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getPhone()) ?>"/>
                        </div>
                    </div>
                </li>
				<li class="fields">
                    <div class="field">
	                	<label><?php if($this->getEmail()): ?><?php echo $this->__($this->getEmail()); ?><?php else: ?><?php echo $this->__("Email:"); ?><?php endif; ?><span class="required"><em>*</em></span></label>
    	            	<div class="input-box">
                        	<input type="text" name="email" size="45" class="input-text validate-email required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"/>
                        </div>
                    </div>
                    <?php if($this->getWebsiteHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getWebsite()): ?><?php echo $this->__($this->getWebsite()); ?><?php else: ?><?php echo $this->__("Website:"); ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="website" size="45" class="input-text" value="<?php echo $this->escapeHtml($this->getFormData()->getWebsite()) ?>"/> 
                        </div>
                    </div>
                    <?php endif; ?>
                </li>
                <li class="fields">
                    <div class="field">
                        <label><?php if($this->getDescription()): ?><?php echo $this->__($this->getDescription()); ?><?php else: ?><?php echo $this->__("Business Description:"); ?><?php endif; ?></label>
                        <div class="input-box">
                            <textarea name="desc" cols="75" rows="2" class="input-text"><?php echo $this->escapeHtml($this->getFormData()->getDesc()) ?></textarea>
                        </div>
                    </div>
                    <?php if($this->getDateTimeHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getDateTime()): ?><?php echo $this->__($this->getDateTime()); ?><?php else: ?><?php echo $this->__("Date Time:"); ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="date_time" id="date_time" size="45" class="input-text validate-date" placeholder="dd/mm/yyyy HH:MM:SS" value="<?php echo $this->escapeHtml($this->getFormData()->getDateTime()) ?>"/>  <img title="Select date" id="date-picker-cal" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>">
                        </div>
                    </div>
					<script type="text/javascript">// <![CDATA[
						Calendar.setup({
							inputField : 'date_time',
							ifFormat : '%d/%m/%Y %H:%M:%S',
							button : 'date-picker-cal',
							align : 'Br',
							singleClick : true ,
							showsTime : true
						});
					// ]]></script>
					<?php endif; ?>
                </li>
				<li class="fields">
					<?php if($this->getUploadFileHide()): ?>
					<div class="field">
                    	<label><?php if($this->getUploadFile()): ?><?php echo $this->__($this->getUploadFile()); ?><?php else: ?><?php echo $this->__("Upload File:"); ?><?php endif; ?></label>
                        <div class="input-box"  id="uploadFile_div">
                        	<input type="file" id="file" name="file[]" size="45" class="input-text" multiple/>&nbsp;&nbsp;&nbsp;
							<a id="clearfile" onclick="clearFileInputField('uploadFile_div')" 
                         href="javascript:void(0);"><?php echo $this->__("Clear Uploaded File");?></a>
						 </div>
                    </div>
					<?php endif; ?>
                    
                    <?php if($this->getFieldOneHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getExtraFieldOne()): ?><?php echo $this->__($this->getExtraFieldOne()); ?><?php else: ?><?php echo $this->__("Extra Field 1:"); ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="extra_field_one" size="45" class="input-text" value="<?php echo $this->escapeHtml($this->getFormData()->getExtraFieldOne()) ?>"/> 
                        </div>
                    </div>
                    <?php endif; ?>
				</li>
                
				<li class="fields">
					<?php if($this->getFieldTwoHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getExtraFieldTwo()): ?><?php echo $this->__($this->getExtraFieldTwo()); ?><?php else: ?><?php echo $this->__("Extra Field 2:"); ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="extra_field_two" size="45" class="input-text" value="<?php echo $this->escapeHtml($this->getFormData()->getExtraFieldTwo()) ?>"/> 
                        </div>
                    </div>
                    <?php endif; ?>
					<?php if($this->getFieldThreeHide()): ?>
                    <div class="field">
                    	<label><?php if($this->getExtraFieldThree()): ?><?php echo $this->__($this->getExtraFieldThree()); ?><?php else: ?><?php echo $this->__("Extra Field 3:"); ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="extra_field_three" size="45" class="input-text" value="<?php echo $this->escapeHtml($this->getFormData()->getExtraFieldThree()) ?>"/> 
                        </div>
                    </div>
                    <?php endif; ?>
				</li>
                <li class="fields last">
					<?php if($this->getCaptchaHide()): ?>
					<?php //echo $this->getChildHtml('captcha') ?>
							<label><?php if($this->getCaptcha()): ?><?php echo $this->__($this->getCaptcha()); ?><?php else: ?><?php echo $this->__('Please type the letters below')?><?php endif; ?><span class="required"><em>*</em></span></label>
							<div class="clear"></div>
							<div class="captcha-main">
								<div id="captcha" class="captcha-left">
									<?php $image_name = Mage::helper('inquiry')->createCaptchaImage(); ?>
									<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."inquiry/captcha/".$image_name ;?>" id="captcha_image"/>
								</div> 
							</div> 
							<div id="img_refresh"><img src="<?php echo $this->getSkinUrl('images/inquiry/refresh.png') ?>" onclick="refresh()"></div>
							<div class="clear"></div>
							<input type="text" name="captcha" id="capt" size="24" value="" class="input-text required-entry" />
					<?php endif; ?>
            	</li>
			</ul>
			<div class="clear"></div>
			<div class="button-set">
				<button id="submit-inquiry"  type="submit" name="SUBMIT"  class="button" value="SUBMIT"><span><span><?php if($this->getBtnText()): ?><?php echo $this->__($this->getBtnText()); ?><?php else: ?><?php echo $this->__("Submit"); ?><?php endif;  ?></span></span></button>
		     </div>
        </div>
    </form>
    <div class="clear"></div>
</div>

<script type="text/javascript">
//< ![CDATA[
var customForm = new VarienForm('dealerInquiry');
//]]>
	function isNumberKey(evt)
	{
		 var charCode = (evt.which) ? evt.which : evt.keyCode
		 if (charCode > 31 && (charCode < 48 || charCode > 57))
		 {
		 	return false;
		}		
		 return true;
	} 
	

</script>