<?php
/***************************************************************************
 Extension Name	: Dealer Inquiry
 Extension URL	: http://www.magebees.com/magento-dealer-inquiry-extension.html
 Copyright		: Copyright (c) 2015 MageBees, http://www.magebees.com
 Support Email	: support@magebees.com 
 ***************************************************************************/
?>
<?php
$success_tital = Mage::getStoreConfig('inquiry/general/success_tital');
$success_des = Mage::getStoreConfig('inquiry/general/success_des');
?>

<div id="about-copy" class="inquiryThank">
	<h1><?php if($success_tital): ?><?php echo $success_tital; ?><?php endif; ?></h1>
	<p>
		<?php if($success_des): ?>
		<?php echo $success_des; ?>
		<?php endif;  ?>
	</p>
</div>