<?php

/**
 * @copyright  Copyright (c) 2010 Capacity Web Solutions Pvt. Ltd  (http://www.capacitywebsolutions.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>


<?php
$success_tital = Mage::getStoreConfig('inquiry/general/success_tital');
$success_des = Mage::getStoreConfig('inquiry/general/success_des');
?>

<div id="about-copy" class="inquiryThank">
	<h1><?php if($success_tital): ?><?php echo $success_tital; ?><?php endif; ?></h1>
	<p>
		<?php if($success_des): ?>
		<?php echo $success_des; ?>
		<?php endif;  ?>
	</p>
</div>